spring:
  application:
    name: monitor-service
server:
  port: 7041
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
turbine:
  aggregator:
    cluster-config: default
  cluster-name-expression: new String("default")
  app-config: user-service,blog-service,ginkgo-service
  instanceUrlSuffix: actuator/hystrix.stream
