eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    prefer-ip-address: true

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-cloud-auth?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false
    username: root
    password: 12345678
#    url: jdbc:mysql://114.116.73.128:3306/user_server?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false
#    username: root
#    password: password