spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
        git:
          uri: https://github.com/www-zhangyu/camellia_config.git
          search-paths: config
          username: www-zhangyu
          password:
      label: master
    bus:
      enabled: true
      trace:
        enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh

#---
#spring:
#  profiles:
#    active: config8770
#server:
#  port: 8770


#---
#spring:
#  profiles:
#    active: config8771
#server:
#  port: 8771
